# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cpptrans_cdf <- function(originaldata) {
    .Call(`_safeBart_cpptrans_cdf`, originaldata)
}

cpptrans_cdf_test <- function(originaldata, testdata) {
    .Call(`_safeBart_cpptrans_cdf_test`, originaldata, testdata)
}

scale_response <- function(a, b, c, d, y) {
    .Call(`_safeBart_scale_response`, a, b, c, d, y)
}

get_original <- function(low, high, sp_low, sp_high, sum_preds) {
    .Call(`_safeBart_get_original`, low, high, sp_low, sp_high, sum_preds)
}

get_original_TE <- function(low, high, sp_low, sp_high, sum_preds) {
    .Call(`_safeBart_get_original_TE`, low, high, sp_low, sp_high, sum_preds)
}

unfold <- function(p_ind, output_dyck, length) {
    .Call(`_safeBart_unfold`, p_ind, output_dyck, length)
}

fold <- function(output_dyck, length, height) {
    invisible(.Call(`_safeBart_fold`, output_dyck, length, height))
}

dyck_path <- function(output_dyck, length) {
    invisible(.Call(`_safeBart_dyck_path`, output_dyck, length))
}

#' @description Test draw of trees of given length
#' @export
wrapper_dyck_path <- function(length) {
    .Call(`_safeBart_wrapper_dyck_path`, length)
}

find_term_nodes <- function(tree_table) {
    .Call(`_safeBart_find_term_nodes`, tree_table)
}

get_treepreds <- function(original_y, num_cats, alpha_pars, originaldata, treetable) {
    .Call(`_safeBart_get_treepreds`, original_y, num_cats, alpha_pars, originaldata, treetable)
}

#' @title For a set of trees, obtain tree matrices with predictions, and obtain model weights
#' @export
get_treelist <- function(original_y, num_cats, alpha_pars, beta_pow, originaldata, treetable_list) {
    .Call(`_safeBart_get_treelist`, original_y, num_cats, alpha_pars, beta_pow, originaldata, treetable_list)
}

get_test_probs <- function(weights, num_cats, testdata, treetable) {
    .Call(`_safeBart_get_test_probs`, weights, num_cats, testdata, treetable)
}

#' @title Given tree tables and model weights, obtain predicted probabilities for test data.
#' @export
get_test_prob_overall <- function(weights, num_cats, testdata, treetable_list) {
    .Call(`_safeBart_get_test_prob_overall`, weights, num_cats, testdata, treetable_list)
}

#' @title Draw a set of trees from the prior.
#' @export
draw_trees <- function(lambda, num_trees, seed, num_split_vars, num_cats) {
    .Call(`_safeBart_draw_trees`, lambda, num_trees, seed, num_split_vars, num_cats)
}

#' @title Safe-Bayesian Random Forest. Initial test function.
#' @export
sBayesRF <- function(lambda, num_trees, seed, num_cats, y, original_datamat, alpha_parameters, beta_par, test_datamat) {
    .Call(`_safeBart_sBayesRF`, lambda, num_trees, seed, num_cats, y, original_datamat, alpha_parameters, beta_par, test_datamat)
}

#' @title Safe-Bayesian Random Forest
#'
#' @description An implementation of the Safe-Bayesian Random Forest described by Quadrianto and Ghahramani (2015)
#' @param lambda A real number between 0 and 1 that determines the splitting probability in the prior (which is used as the importance sampler of tree models). Quadrianto and Ghahramani (2015) recommend a value less than 0.5 .
#' @param num_trees The number of trees to be sampled.
#' @param seed The seed for random number generation.
#' @param num_cats The number of possible values for the outcome variable.
#' @param y The training data vector of outcomes. This must be a vector of integers between 1 and num_cats.
#' @param original_datamat The original training data. Currently all variables must be continuous. The training data does not need to be transformed before being entered to this function.
#' @param alpha_parameters Vector of prior parameters.
#' @param beta_par The power to which the likelihood is to be raised. For BMA, set beta_par=1.
#' @param original_datamat The original test data. This matrix must have the same number of columns (variables) as the training data. Currently all variables must be continuous. The test data does not need to be transformed before being entered to this function.
#' @export
sBayesRF_onefunc <- function(lambda, num_trees, seed, num_cats, y, original_datamat, alpha_parameters, beta_par, test_datamat) {
    .Call(`_safeBart_sBayesRF_onefunc`, lambda, num_trees, seed, num_cats, y, original_datamat, alpha_parameters, beta_par, test_datamat)
}

#' @title Safe-Bayesian Random Forest in C++
#'
#' @description An implementation of the Safe-Bayesian Random Forest described by Quadrianto and Ghahramani (2015)
#' @param lambda A real number between 0 and 1 that determines the splitting probability in the prior (which is used as the importance sampler of tree models). Quadrianto and Ghahramani (2015) recommend a value less than 0.5 .
#' @param num_trees The number of trees to be sampled.
#' @param seed The seed for random number generation.
#' @param num_cats The number of possible values for the outcome variable.
#' @param y The training data vector of outcomes. This must be a vector of integers between 1 and num_cats.
#' @param original_datamat The original training data. Currently all variables must be continuous. The training data does not need to be transformed before being entered to this function.
#' @param alpha_parameters Vector of prior parameters.
#' @param beta_par The power to which the likelihood is to be raised. For BMA, set beta_par=1.
#' @param original_datamat The original test data. This matrix must have the same number of columns (variables) as the training data. Currently all variables must be continuous. The test data does not need to be transformed before being entered to this function.
#' @export
sBayesRF_onefunc_arma <- function(lambda, num_trees, seed, num_cats, y, original_datamat, alpha_parameters, beta_par, test_datamat) {
    .Call(`_safeBart_sBayesRF_onefunc_arma`, lambda, num_trees, seed, num_cats, y, original_datamat, alpha_parameters, beta_par, test_datamat)
}

#' @title Parallel Safe-Bayesian Random Forest
#'
#' @description A parallelized implementation of the Safe-Bayesian Random Forest described by Quadrianto and Ghahramani (2015)
#' @param lambda A real number between 0 and 1 that determines the splitting probability in the prior (which is used as the importance sampler of tree models). Quadrianto and Ghahramani (2015) recommend a value less than 0.5 .
#' @param num_trees The number of trees to be sampled.
#' @param seed The seed for random number generation.
#' @param num_cats The number of possible values for the outcome variable.
#' @param y The training data vector of outcomes. This must be a vector of integers between 1 and num_cats.
#' @param original_datamat The original training data. Currently all variables must be continuous. The training data does not need to be transformed before being entered to this function.
#' @param alpha_parameters Vector of prior parameters.
#' @param beta_par The power to which the likelihood is to be raised. For BMA, set beta_par=1.
#' @param original_datamat The original test data. This matrix must have the same number of columns (variables) as the training data. Currently all variables must be continuous. The test data does not need to be transformed before being entered to this function.
#' @param ncores The number of cores to be used in parallelization.
#' @return A matrix of probabilities with the number of rows equl to the number of test observations and the number of columns equal to the number of possible outcome categories.
#' @export
sBART_onefunc_parallel <- function(lambda, num_models, num_trees, seed, ytrain, original_datamat, beta_par, test_datamat, ncores, outsamppreds, nu, a, lambdaBART, valid_trees, tree_prior, imp_sampler, alpha_BART, beta_BART, s_t_hyperprior, p_s_t, a_s_t, b_s_t, lambda_poisson, fast_approx) {
    .Call(`_safeBart_sBART_onefunc_parallel`, lambda, num_models, num_trees, seed, ytrain, original_datamat, beta_par, test_datamat, ncores, outsamppreds, nu, a, lambdaBART, valid_trees, tree_prior, imp_sampler, alpha_BART, beta_BART, s_t_hyperprior, p_s_t, a_s_t, b_s_t, lambda_poisson, fast_approx)
}

#' @title Parallel Safe-Bayesian Causal Forest
#'
#' @description A parallelized implementation of the Safe-Bayesian Random Forest described by Quadrianto and Ghahramani (2015)
#' @param lambda A real number between 0 and 1 that determines the splitting probability in the prior (which is used as the importance sampler of tree models). Quadrianto and Ghahramani (2015) recommend a value less than 0.5 .
#' @param num_trees The number of trees to be sampled.
#' @param seed The seed for random number generation.
#' @param num_cats The number of possible values for the outcome variable.
#' @param y The training data vector of outcomes. This must be a vector of integers between 1 and num_cats.
#' @param original_datamat The original training data. Currently all variables must be continuous. The training data does not need to be transformed before being entered to this function.
#' @param alpha_parameters Vector of prior parameters.
#' @param beta_par The power to which the likelihood is to be raised. For BMA, set beta_par=1.
#' @param original_datamat The original test data. This matrix must have the same number of columns (variables) as the training data. Currently all variables must be continuous. The test data does not need to be transformed before being entered to this function.
#' @param ncores The number of cores to be used in parallelization.
#' @return A matrix of probabilities with the number of rows equl to the number of test observations and the number of columns equal to the number of possible outcome categories.
#' @export
sBCF_onefunc_parallel <- function(lambda_mu, lambda_tau, num_models, num_trees_mu, num_trees_tau, seed, ytrain, original_datamat, ztrain, pihat_train, beta_par, test_datamat, test_z, test_pihat, ncores, outsamppreds, nu, a_mu, a_tau, lambdaBCF, valid_trees, tree_prior, imp_sampler, alpha_BCF_mu, beta_BCF_mu, alpha_BCF_tau, beta_BCF_tau, include_pi2, fast_approx, PIT_propensity) {
    .Call(`_safeBart_sBCF_onefunc_parallel`, lambda_mu, lambda_tau, num_models, num_trees_mu, num_trees_tau, seed, ytrain, original_datamat, ztrain, pihat_train, beta_par, test_datamat, test_z, test_pihat, ncores, outsamppreds, nu, a_mu, a_tau, lambdaBCF, valid_trees, tree_prior, imp_sampler, alpha_BCF_mu, beta_BCF_mu, alpha_BCF_tau, beta_BCF_tau, include_pi2, fast_approx, PIT_propensity)
}

